export const MyConsts = {
    NODE_PRPNAME_PARAM_ROLE_STATE: 'paramState',
    NODE_PRPNAME_PARAM_ROLE_POWER: 'paramP',
    NODE_STATE_ON: 1,
    NODE_STATE_OFF: 0,
    NODE_STATE_UNKNOWN: -1,    
    NODE_TYPE_LEP: 2,
    NODE_TYPE_PS: 5,
    NODE_LEP_WIDTH: 100,
    NODE_LEP_HEIGHT: 6,
    NODE_LEP_Y_OFFSET: 10,
    NODE_PS_RADIUS: 10,

  };

